services:
  zenoh:
    image: eclipse/zenoh:latest
    container_name: zenoh
    ports:
      - "7447:7447"
    networks:
      - kuksa

  databroker:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:latest
    container_name: databroker
    command: ["--insecure", "--vss", "/app/vss.json"]
    volumes:
      - type: bind
        source: ./own_vss.json
        target: /app/vss.json
        read_only: true
    ports:
      - "30000:55555"
    networks:
      - kuksa

  databroker-cli:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker-cli:main
    container_name: databroker-cli
    depends_on:
      - databroker
    command:
      - "--server"
      - "databroker:55555"
    stdin_open: true
    tty: true
    networks:
      - kuksa

  can-provider:
    image: ghcr.io/eclipse-kuksa/kuksa-can-provider/can-provider
    environment:
      LOG_LEVEL: "debug"
    container_name: can-provider
    depends_on:
      - databroker
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./config/dbc_feeder.ini
        target: /config/dbc_feeder.ini
        read_only: true
      - type: bind
        source: ./ModelCarCAN.dbc
        target: /mapping/ModelCarCAN.dbc
        read_only: true
      - type: bind
        source: ./own_vss.json
        target: /mapping/own_vss.json
        read_only: true
      - type: bind
        source: ./candump-2018-09-29_032339.log
        target: /data/candump-2018-09-29_032339.log
        read_only: true
      - type: bind
        source: ./dbc_default_values.json
        target: /mapping/dbc_default_values.json
    command: ["--config", "/config/dbc_feeder.ini"]



  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
      target: subscriber
    container_name: subscriber
    depends_on:
      - zenoh
    environment:
      - RUST_LOG=debug,zenoh=debug
    networks:
      - kuksa

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
      target: publisher
    container_name: publisher
    depends_on:
      - zenoh
    environment:
      - RUST_LOG=debug,zenoh=debug
    networks:
      - kuksa

  provider:
    build:
      context: .
      dockerfile: Dockerfile
      target: provider
    container_name: provider
    depends_on:
      - zenoh
      - databroker
    environment:
      - RUST_LOG=info,zenoh=debug,RUST_BACKTRACE=1
    networks:
      - kuksa


networks:
  kuksa:
    driver: bridge